console.log("test example after triggered");
console.log("test example after triere");
console.log("test example after triere");
console.log("test example after trire");
console.log("test example after triggd");
console.log("test example after tggd");
console.log("test example aftegged");
console.log("test example afggered");
console.log("test example ariggered");
(function () {
  const vscode = aquireVsCodeApi();
  console.log("test example after triggered");
  console.log("test example after triere");
  console.log("test example after triere");
  console.log("test example after trire");
  console.log("test example after triggd");
  console.log("test example after tggd");
  console.log("test example aftegged");
  console.log("test example afggered");
  console.log("test example ariggered");
});
